### ISSUE TITLE
[Feature request] Add 'remove' or 'uninstall' command

### ISSUE THREAD

**Issue by mzac** [alexellis/arkade#101]
## Expected Behaviour
Should be able to remove or uninstall an app without having to delete it manually

## Current Behaviour
To remove or uninstall an app you have to use kubectl commands

## Possible Solution
The remove or uninstall feature could be integrated into arkade

## Context
I installed an app and wanted to remove it

## Your Environment

* v1.17.4+k3s1

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:40Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/arm"}
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a
Linux pi3 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

* What arkade version is this?

```
arkade version
Version: 0.2.8
Git Commit: 8f311a3ad529cff36e854b3a3ab8f07cd0195105
```

**Comment by goffinf** [comment]
Hmm why not-approved ?

This seems like a reasonable feature request and something I also wanted to do shortly after using arkade to install and app as a test ?

**Comment by pyramation** [comment]
I just ran into this when debugging an install. Wanted to uninstall and then install again since pods weren't running, and wanted to debug the state just before install occured.

**Comment by alexellis** [comment]
You can install apps twice, the second time should overwrite the first, and / or upgrade it. For OpenFaaS, that's certainly the case. For others removal and uninstallation is tricky and varies per app.

This is not in scope for the time being and has very little demand from the community, but a high cost to implement and maintain for each app.

**Comment by goffinf** [comment]
I see. That somewhat puts me off using arkade TBH. I believe that any installer of any kind should always provide an uninstall capability, and without it ... well its like doing unit testing only for the happy path. The use cases are obvious here.  Build it and they will come ?

**Comment by alexellis** [comment]
@goffinf entirely up to you sir, whether you are put off or not unfortunately doesn't change the effort involved in maintaining this feature for every app.

Which particular apps are you wanting to remove? Most are installed with helm3 and you can simply run `~/.arkade/bin/helm3/helm ls` to see which apps you have and then run `helm remove` to uninstall. Not every app is installed with helm, but where we can do so then they are.

**Comment by goffinf** [comment]
Sorry Alex, this has been niggling me. I get the compromise to be struck between the amount of effort required to implement an additional feature vs. the benefit to the broader user base (as opposed to just the person that raised it). I am aware that I can fill this particular gap another way, but it somewhat diminishes the value of arkade if I need to switch out to do something that it feels like it should be able to.

Maybe it’s just the tone of the dismissal that’s bothering me and if I understood more about the why I would feel differently. But I have watched a lot of your talks on the various projects that you manage and this seems very much at odds with the idea simplifying a complex process that you often promote (and I happen to agree with). I have heard you say increasingly how difficult it is manage the effort required to maintain open source projects without some level of sponsorship and I have every sympathy with that position. But at the end of the day, a piece of software has to solve enough of a problem in order to find its utility and encourage that very support. Agreed, it doesn’t need to cover every ‘edge case’, but this one is pretty core isn’t it ? Whilst in principle it would be nice to think that in general people could/should support open source efforts regardless of whether they actually use a particular project, in practice, we are drawn to those which are germane to our problem space and if they lack some fundamental feature, and the maintainer shows no interest in supporting it, well, we often move on.

It’s a trait of mine that I fall into the ‘finisher’ profile. The problem I see often is great beginnings eventually fall short because they don’t follow through to complete a full enough set of core features  ... notwithstanding the need to pursue that via some form of ‘agile’ delivery. We all like cool stuff, but ultimately, it’s doing the core features really well that will win out.

Whether or not arkade supports uninstall is actually not that big a deal to me personally. I’m a big fan of all of your work and I want that to be successful in every sense. I like the philosophy that some of the things that you do may turn out to be stepping stones to better ideas or help us all understand the problem space more fully.

I’m am just stung by the position you have taken here or perhaps the way you have expressed it.

Anyway, I’m going to wish you every success, but say that ‘I’m out’ (a little dragons-den humour :-)

Warm regards

Fraser.

**Comment by alexellis** [comment]
@goffinf would you be open to answering my question above?

https://github.com/alexellis/arkade/issues/101#issuecomment-648137586

Which apps did you want to remove?

Did you know that they can all be managed with the version of helm that arkade downloads? `helm ls` / `helm remove` is pretty much all you need for most of them.
