### ISSUE TITLE
arkade get, shouldn't re-download

### ISSUE THREAD

**Issue by wahmedswl** [alexellis/arkade#233]
Hi, Arkade should not download same pkg multiple times. Every invoke of ```arkade get``` re-download the pkg.

Thanks

**Comment by alexellis** [comment]
Hi @wahmedswl 

I appreciate the interest in arkade, however I'm going to be closing this issue because:

1) you deleted the issue template
2) you provided no context, evidence or screen output

If you want to participate in the project, please follow the contribution guidelines and templates.

Alex

**Comment by wahmedswl** [comment]
Thanks understandable and will re-post with the template. But, template is to help in issue evaluation and its clear from the description i guess you understand what this issue is about.

But, i do abide the rules, no problem :-)
Thanks

**Comment by alexellis** [comment]
The template absolutely is of use - it asks what happened, what you expected, asks for step by step instructions along with your suggested solutions.
