### ISSUE TITLE
envsubst

### ISSUE THREAD

**Issue by hholst80** [alexellis/arkade#402]
RFC 
include https://github.com/a8m/envsubst 

use case:
```sh
[root@tugboat] ~/app/controlplane/backend (master) ⚡ 
❯ kubectl kustomize | grep '$NAMESPACE' | wc                                                                                                                                                                         ⏎
     18      36     436

[root@tugboat] ~/app/controlplane/backend (master) ⚡ 
❯ kubectl kustomize . | env -i NAMESPACE=backend PATH="$PATH" envsubst -no-{unset,empty} | kubectl apply -f - --dry-run=server
serviceaccount/backend unchanged (server dry run)
role.rbac.authorization.k8s.io/backend unchanged (server dry run)
rolebinding.rbac.authorization.k8s.io/backend unchanged (server dry run)
configmap/config configured (server dry run)
secret/tls-secret unchanged (server dry run)
service/haproxy unchanged (server dry run)
deployment.apps/haproxy unchanged (server dry run)

❯ 
```

**Comment by hholst80** [comment]
Great job guys closing an issue after 10 months with "invalid" wo further information. This is how you build a failed state.

**Comment by Shikachuu** [comment]
Hey @hholst80, I am sorry if you feel this way, but the issue isn't closed yet!
Can you give us some guidance, where and how should we update our bot's invalid template comment?
I would be much appreciated!

**Comment by alexellis** [comment]
Derek added the label because the issue template wasn't filled in. Sorry that you get this way, but it's not personal.

Go ahead and fill out the template properly and we can remove the label and consider your request.

If you don't want to follow the contribution process, that's ok. Just let us know and we will get this closed for you.

Thanks for your interest in arkade
