### ISSUE TITLE
[APP] support TFENV

### ISSUE THREAD

**Issue by MushiTheMoshi** [alexellis/arkade#479]
Hi there,

Awesome job done here, really helpful. Is there a way to add support for tfenv ?

Regards.

**Comment by MushiTheMoshi** [comment]
TFENV is a version manager for terraform, nowadays projects have multiple versions of terraform is handy to have a version manager https://github.com/tfutils/tfenv

**Comment by Shikachuu** [comment]
/msg template

@MushiTheMoshi Are you still instrested? If thats the case, can you fill the issue template please?

**Comment by MushiTheMoshi** [comment]
I am interested, but never done this before, what should Ï do ? where do I get that template?

**Comment by kvendingoldo** [comment]
Try to use [tenv](https://github.com/tofuutils/tenv) to manager your Terraform/OpenTofu installations.

**Comment by rgee0** [comment]
I'm going to close this due to:

1) inactivity on the issue
2) the project on github appears to have not released for 2 years
3) the build on the project on github appears to be failing

If there is still a desire to see this available via arkade then please open a new issue and complete the issue template.
