### ISSUE TITLE
ark get kubectl uses wrong URL for M1

### ISSUE THREAD

**Issue by vandot** [alexellis/arkade#616]
`ark get kubectl` tries to download tool using wrong URL, right URL is https://storage.googleapis.com/kubernetes-release/release/v1.22.2/bin/darwin/arm64/kubectl

Change is in arch part `arm` to `arm64`

## Expected Behaviour
Running `ark get kubectl` would install kubectl

## Current Behaviour
Running `ark get kubectl` fails with
```
Downloading: kubectl
Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.22.2/bin/darwin/arm/kubectl
Error: incorrect status for downloading tool: 404
```

## Are you a GitHub Sponsor (Yes/No?)

Check at https://github.com/sponsors/alexellis

- [ ] Yes
- [x] No

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Darwin bedanc.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
```

* What arkade version is this?

```
Version: 0.8.13
Git Commit: c09951f5cc840fcb3e9d571e7f4f784c4543e707
```

**Comment by alexellis** [comment]
Hi, this may start to happen to many more CLIs now since arkade uses the binary's architecture to download tools and many tools do not have an M1 binary.

cc @tomtucka

What happens if you run: `arkade get kubectl --arch x86_64`?

In the meantime, if you'd like to send a PR - or if anyone else wants to send one (please also update the unit test) - that'd be appreciated.  

Alex

**Comment by welteki** [comment]
Until this is fixed, running `arkade get kubectl --arch aarch64` works.

**Comment by Shikachuu** [comment]
If this is not taken yet, I'll do it with an ETA of tomorrow morning.

**Comment by vandot** [comment]
@welteki thanks that works
@alexellis as described in the issue `kubectl` has darwin M1 but its on different URL
