### ISSUE TITLE
Feature - Supply tools via config

### ISSUE THREAD

**Issue by scottylaw** [alexellis/arkade#681]
## Expected Behaviour
Suppy tools via a tools.yml file that users can modify to add additional tools they would like to deploy via Arkade. 

## Current Behaviour

Tools are currently hardcoded and require users to submit an issue/PR to get a new tool(s) added or they have to fork this repo and hardcode additional tools in their own repo. 

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [X] No

## Possible Solution

Issues/PRs would obviously still be required to update the default tool config that ships with Arkade. However, to enable users to add additional tools that make sense for them but not necessarily the Arkade community I suggest providing a tools.yml config file containing simply an array of 'tools':

```yml
tools:
  - owner: "openfaas"
    repo: "faas-cli"
    name: "faas-cli"
    description: "Official CLI for OpenFaaS."
    binaryTemplate: |
      {{ if HasPrefix .OS "ming" -}}
      {{.Name}}.exe
      {{- else if eq .OS "darwin" -}}
      {.Name}}-darwin
      {- else if eq .Arch "armv6l" -}}
      {.Name}}-armhf
      {- else if eq .Arch "armv7l" -}}
      {.Name}}-armhf
      {- else if eq .Arch "aarch64" -}}
      {.Name}}-arm64
      {- else -}}
      {.Name}}
      {- end -}}
  - owner: "kubernetes"
    repo: "kubernetes"
    name: "kubectl"
    version: "v1.22.2"
    description: "Run commands against Kubernetes clusters"
    urlTemplate: |
      {{$arch := "arm"}}
      {{- if eq .Arch "x86_64" -}}
      {{$arch = "amd64"}}
      {{- end -}}
      {{- if eq .Arch "aarch64" -}}
      {{$arch = "arm64"}}
      {{- end -}}
      {{- if eq .Arch "arm64" -}}
      {{$arch = "arm64"}}
      {{- end -}}
      {{$ext := ""}}
      {{$os := .OS}}
      {{ if HasPrefix .OS "ming" -}}
      {{$ext = ".exe"}}
      {{$os = "windows"}}
      {{- end -}}
```

## Context

We are using Arkade to maintain the images of tools we use in CI/CD pipelines. We download any number of tools with a single Arkade command and we can then package each of those tools in their own image for use in CI/CD. While reviewing the code to see how I could add additional tools I realized that, with the urlTemplate, Arkade can download just about anything if configured to do so. That said, Arkade is an extremely powerful tool we can leverage to maintain additional tools that fit our use cases but they probably don't make sense to add to Arkade because they aren't popular among the cloud-native community, which is Arkade's focus. It will be much easier to maintain a custom config file than it will be to fork this repo, add our tools, and build/distribute our own version of Arkade.

**Comment by alexellis** [comment]
Hi @scottylaw,

Thanks for your interest in arkade.

Who is "we"? You may find the ["First impressions"](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#first-impressions---introducing-yourself-and-your-use-case) section of the OpenFaaS contribution guide helpful

We are interested in helping you to use arkade, however vast sweeping design changes must be defended. Currently a single binary works well for the community and maintainers. Since Arkade is pulled down fresh in every CI build, there is no likelihood of getting out of date packages.

Arkade also has logic to determine the latest version of every tool - safely (without hitting rate limits).

Rather than coming up with a technical solution and suggesting that is the way arkade should work. Do you mind if we take a different approach and explore the pain you're feeling or the opportunity that you see? 

Alex

**Comment by alexellis** [comment]
/set title: [Feature request] Using arkade to download our own set of custom tools
