### ISSUE TITLE
Download for Windows lacks instructions or usable script

### ISSUE THREAD

**Issue by Jeff-Lowrey** [alexellis/arkade#71]
Since Arkade provides a prebuilt binary for Windows, it should be easy to find and download.

The script at https://get-arkade.dev/ (or https://github.com/alexellis/arkade/blob/master/get.sh) is a bash script and will not run on Windows.

Either the main README should include instructions to manually download the right windows binary, or it should include instructions similar to the one to get the linux distribution, but pointing to a windows cmd or PowerShell script instead of a bash script. Maybe something like 
`curl -sLS https://dl.get-arkade.dev/windows | cmd.exe` or 
`curl -sLS https://dl.get-arkade.dev/windows | powershell`

See also https://github.com/openfaas/workshop/issues/174

**Comment by alexellis** [comment]
Hi Jeff,

You need to use Git Bash, that's how it's meant to be used. None of the apps will work otherwise since we rely on bash being available. 

If you want to use cmd or PowerShell, simply download the binary from the releases page. Since Arkade came from k3sup, I'll check if the note was copied across or not.

The workshop explicitly instructs users to install Git Bash.

Alex

**Comment by alexellis** [comment]
A note has been copied over from k3sup here: https://github.com/alexellis/arkade#get-arkade
