### ISSUE TITLE
Install PostgreSQL on arm64 device

### ISSUE THREAD

**Issue by jevin36** [alexellis/arkade#75]
I was trying to run your todo app tutorial on a Pinebook Pro (aarch64, arm64 device) but unfortunately the official postgresql helm chart only supports pc architecture.

## Expected Behaviour
PostgreSQL Arm64 is used

## Current Behaviour
Arkade exits with an error

## Possible Solution
On https://hub.docker.com/r/arm64v8/postgres there seems to exist an arm64 postgresql version - this would be great if it would be supported somehow (new helm chart using this repo)

## Steps to Reproduce (for bugs)
1. Use arm64 device
2. `arkade install postgresql`
```
Node architecture: "arm64"
Error: only Intel, i.e. PC architecture is supported for this app
```

## Context
Doing the Todo App Golang tutorial with k3d on a Pinebook Pro

## Your Environment
k3d

```
kubectl version 1.17
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
Linux pine 5.6.0-0.42-MANJARO-ARM #1 SMP Sat Mar 14 21:19:14 CET 2020 aarch64 GNU/Linux

NAME="Manjaro-ARM"
ID=manjaro-arm
PRETTY_NAME="Manjaro ARM"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/c/manjaro-arm/"

```

* What arkade version is this?

```
0.2.2
```

**Comment by alexellis** [comment]
Hi thank you for using my blog post and for your interest in this project. The company (Bitnami) that maintains docker images and helm charts for Kubernetes as far as I am aware is not providing support for ARM.

The error you are seeing is because we are aware of this fact and are trying to help you avoid any confusion by installing incorrect charts to your computer.

You can get managed SQL on digitalocean, the rest of the tutorial should work the same. 

Does that make sense?

Alex

**Comment by joebowbeer** [comment]
#942 Bitnami postgresql chart now supports arm64

**Comment by gastonjarju** [comment]
> #942 Bitnami postgresql chart now supports arm64

Hey Joe,
How do I get that install on my MAC?

**Comment by joebowbeer** [comment]
> > #942 Bitnami postgresql chart now supports arm64
> 
> Hey Joe, How do I get that install on my MAC?

The following command installed the bitnami chart in my Rancher Desktop cluster on Apple M1

`ark install postgresql`

For the client install, I followed instructions at https://postgresapp.com/
